import { IUserConfig } from '.';

export const UserConfig: IUserConfig = {
  username: 'un',
  authorities: [{ authority: 'ASSESSMENT_ARCHIVE' }],
  accountNonExpired: true,
  accountNonLocked: true,
  credentialsNonExpired: true,
  enabled: true,
  id: 'id',
  firstName: 'fn',
  lastName: 'ln',
  email: 'example@example.com',
  photoUrl: 'default-avatar.png',
  status: 'ACTIVE',
  companyId: 'companyId',
  authToken: 'token',
  language: 'en',
  languageSuffix: '_en',
  passwordExpired: false,
  subscriptionType: 'SUPPLIER',
  brandsAssociated: ['Test_brand_id'],
  companyProfileView: {
    id: 'c_id',
    name: 'c_name',
    verificationStatus: { id: 20, value: 'VERIFIED' },
    address: {
      addressLine1: '123',
      addressLine2: '123',
      city: 'city',
      state: 'state',
      country: 'country',
      countryCode: 'code',
      zip: '00000',
      latitude: 0,
      longitude: 0,
    },
    companyType: 'SUPPLIER',
    noOfSuppliers: 0,
    noOfStyles: 0,
    facility: [
      {
        id: 'id',
        updateTs: 1601982523949,
        createTs: 1578894652226,
        createdBy: 'created_by',
        lastModifiedBy: 'modified_by',
        entityVersion: 0,
        name: 'f_name',
        companyId: 'id',
        type: 'HQ',
        status: 'ACTIVE',
        completenessScore: 7.0,
        createdCompanyId: 'id',
        noOfAssessments: 0,
        createdCompanyName: 'c_cname',
        certificateList: [],
      },
    ],
    pcScore: 37,
    incompleteFields: ['contactInfo', 'description', 'logo', 'facility'],
  },
  tiersAssociated: [],
  ouModuleAttributeValueDataViews: [],
  hasAdminGroup: true,
  consentSaved: true,
};
